
const wally_sheets={}
export default wally_sheets


import { GoogleSpreadsheet } from 'google-spreadsheet';
import { JWT } from 'google-auth-library';


import { parse as csv_parse } from "csv-parse/sync"
import { stringify as csv_stringify } from "csv-stringify/sync"
import pfs from "node:fs/promises"
import path from "path"


let load_csv=async function(path)
{
	let data=await pfs.readFile(path,"utf8")
	let csv=csv_parse(data,{relax_column_count:true,columns:true})
	return csv
}

let load_doc=async function(id)
{
	// Initialize auth - see https://theoephraim.github.io/node-google-spreadsheet/#/guides/authentication
	const serviceAccountAuth = new JWT({
	  // env var values here are copied from service account credentials generated by google
	  // see "Authentication" section in docs for more info
	  email: process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL,
	  key: process.env.GOOGLE_PRIVATE_KEY,
	  scopes: ['https://www.googleapis.com/auth/spreadsheets'],
	});

// console.log( process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL )
// console.log( process.env.GOOGLE_PRIVATE_KEY )

	// sheet must be shared with process.env.GOOGLE_SERVICE_ACCOUNT_EMAIL for this to work
	const doc = new GoogleSpreadsheet(id, serviceAccountAuth);

	await doc.loadInfo(); // loads document properties and worksheets

	return doc
}


let load_sheet=async function(doc,name)
{
	let sheet=( doc.sheetsByIndex[name] || doc.sheetsByTitle[name] ) // number or title
	await sheet.loadCells()
	let maxy=0
	let rows=[]
	for( let yidx=0 ; yidx<sheet.rowCount ; yidx++ )
	{
		let row=[]
		let maxx=0
		for( let xidx=0 ; xidx<sheet.columnCount ; xidx++ )
		{
			let cell=await sheet.getCell(yidx,xidx)
			if( typeof cell.value != "object" ) // empty check
			{
				row[xidx]=cell.value // may be string or number or bool
				maxx=xidx+1
			}
		}
		for( let xidx=0 ; xidx<maxx ; xidx++ ) { if(!row[xidx]) { row[xidx]=[] } } //fill holes
		if( maxx>0 )
		{
			rows[yidx]=row
			maxy=yidx+1
		}
	}
	for( let yidx=0 ; yidx<maxy ; yidx++ ) { if(!rows[yidx]) { rows[yidx]=[] } } //fill holes
	return rows
}

let save_csv=async function(path,rows)
{
	let csvs=csv_stringify( rows )
	await pfs.writeFile( path , csvs )
}

wally_sheets.start=async function(opts)
{
	let doc=await load_doc("12rsvB81cRoE5n7mdCpvCjj38OqTFjBSVzJNOfL4ApPY")
	let rows=await load_sheet(doc,"Sheet1")
	console.log(rows)
}

