#!/usr/bin/env bash

wget "https://huggingface.co/Mozilla/llava-v1.5-7b-llamafile/resolve/main/llava-v1.5-7b-q4.llamafile?download=true" --output-document=llava.llamafile
chmod +x llava.llamafile
cp llama-llava llama




