#!/usr/bin/env bash

# first install a require script
if ! [[ -x "$(command -v require.sh)" ]] ; then

        echo " we need sudo to install require.sh to /usr/local/bin "
        sudo wget -O /usr/local/bin/require.sh https://raw.githubusercontent.com/xriss/require.sh/main/require.sh
        sudo chmod +x /usr/local/bin/require.sh

fi

# commands

require.sh git
require.sh clang
require.sh gcc
require.sh make
require.sh luajit
require.sh patchelf
require.sh zip


# build llama.cpp

rm -rf llama.cpp
git clone git@github.com:ggerganov/llama.cpp.git
cd llama.cpp
make
cd ..


# choose correct llama

cp llama-cpp llama


# copy model

mkdir gguf
wget "https://huggingface.co/TheBloke/Mistral-7B-OpenOrca-GGUF/resolve/main/mistral-7b-openorca.Q4_K_M.gguf" -O gguf/mistral-7b-openorca.Q4_K_M.gguf

